# Generated by Django 5.2.6 on 2025-09-27 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "db_table": "brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("category", models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UnitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=80)),
            ],
            options={
                "db_table": "unit_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to="app_core.brand",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns",
                "ordering": ["brand__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "external_ref",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "storage_url",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="app_core.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "assets",
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="SparkUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "default_weight",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=5),
                ),
                (
                    "unit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spark_units",
                        to="app_core.unittype",
                    ),
                ),
            ],
            options={
                "db_table": "spark_units",
            },
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["brand"], name="campaigns_brand_i_c2d4bd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="campaign",
            unique_together={("brand", "name")},
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["campaign"], name="assets_campaig_07f343_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["external_ref"], name="assets_externa_d722b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sparkunit",
            index=models.Index(
                fields=["unit_type"], name="spark_units_unit_ty_e886c6_idx"
            ),
        ),
    ]
